[Nancy Data]
CDDrive1=c:
CDDrive2=c::
HDDrive=c:

IDPath=\sck\
CifTreePath=\sck\CifTree\
HDVideoPath=\sck\HDVideo\
CDVideoPath=\sck\CDVideo\
HDSoundPath=\sck\HDSound\
CDSoundPath=\sck\CDSound\
LoadSavePath=\sck\

RunEntirelyFromCDDrive=0				; 1=run all app from cdrom, 0=run normal
CifTreeAndFilesOnCD=0					; 1=all cif/tree files on CDROM, 0=tree on hard drive
TestingModeEnabled=0					; 1=enable test-only mode, 0=not enabled
ExternalCifFileChecking=1				; 1=look for cif files external to tree, 0=don't look
DebugOutput=1							; 1=enable debug output (huge), 0=not enabled
RunInWindowedMode=0						; 1=run in a window, 0=run full-screen exclusive mode

; 640x480 aspect=1.33 : 1
MaxXAxisTravelPerMove=195				; max x travel per render loop
MaxYAxisTravelPerMove=150				; max y travel per render loop

SoundSystemIsActive=1			; 1=sound, 0=no sound
ForceSoundBufSize=0			; 0=use default, 1=force size
SoundBufSize=4096			; size used if forced
SoundBufSkip=6				; raise if sound skips, lower if video not synching
UseDirectSound=1			; 0=MME, 1=DirectSound

ClosedCaptioning=1
PlayerSpeech=1
CharacterSpeech=1

VoiceMasterVolume=54
MusicMasterVolume=54
SpecialEffectsMasterVolume=51
SwapLeftAndRightSoundChannels=0

PrimaryVideoNonSoundTimeDelay=300
PrimaryVideoNonSoundFrameTime=66

SystemQualityForPrimaryVideo=0
InstallationType=0
PlayerWonTheGame=StillWorkingOnIt

[SystemInfo]
SystemName=C784235-A
OEMId=0x0
MinCodeAddress=0x400000
MaxCodeAddress=0x7FFFFFFF
PageSize=0x1000
AllocationGranularity=0x10000
ProcessorType=Pentium
CDTransferSpeed(bytes/sec)=138042.59



